services:
    _defaults:
        autowire: true
        autoconfigure: true

    Alengo\SuluContentExtraBundle\Content\Enhancer\NavigationLinkEnhancer: ~

    Alengo\SuluContentExtraBundle\Content\Resolver\NavigationLinkTypeResolver:
        tags:
            - { name: 'sulu_content.content_resolver', type: 'navlink' }
